Describe validation and how to opt-out of it
RConsortium/OOP-WG pull request #44
Opened 2020-10-06 20:51 UTC by hadley

Fixes #25

2020-10-06 21:27 UTC, lawremi approved these changes

2020-10-10 12:50 UTC, hadley commented
@mmaechler @ltierney does this look ok to you? (goal is to capture discussion in the linked issue, not to declare this as the final answer)

2020-10-15 23:29 UTC, ltierney approved these changes

2020-10-16 07:24 UTC, mmaechler requested changes
Really a good idea to have both  `eventuallyValid(object, *)`  and `implicitlyValid()` with the small crucial difference as proposed.

I'd prefer to call the 2nd argument `FUN` or similar as I would want to require a function there, and the word `code` is too vague for that..

2020-10-16 13:21 UTC, merged